apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
data:
  QIWI_SECRET: c29tZV9hcGlfdG9rZW4K
  QIWI_API_TOKEN: c29tZV9hcGlfdG9rZW4K
  PHONE_NUMBER: K251bWJlcgo=
  GOOGLE_CLIENT_ID: c29tZV9jbGllbnRfaWQK
  GOOGLE_CLIENT_SECRET: c29tZV9zZWNyZXQK