apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: bmV3X2Ri
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_HOST: bG9jYWxob3N0
stringData:
  PGDATA: /var/lib/postgresql/data/pgdata